import { PresetScenario, SocialClass, ActionTactic, SystemRegime } from '../types/simulation';

export const DEFAULT_CONFIG = {
  populationProletariat: 30,
  populationCapitalist: 5,
  populationTechnocracy: 4,
  populationReserveArmy: 8,
  alphaInitial: 0.25,
  alarmThreshold: 0.60,
  machineReactionFactor: 0.05,
  infrapowerMin: 0.10,
  infrapowerMax: 0.77,
  phiBase: 0.20,
  phiVolatility: 0.15,
  spatialRadius: 18,
  mechanizationSpeed: 4.5,
  baseWage: 5.0,
};

export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    id: 'p-perro-duo',
    title: 'Ejercicio Original P.Perro: Dúo Sani & Djago',
    subtitle: 'Módulos v1 a v4: Herbert Simon, Infrapoder y Afinidad Electiva',
    description: 'Reproducción interactiva de los scripts fundacionales con los sujetos Sani (int=10) y Djago (int=15) frente a The Machine (ext=100, alfa=0.25). Permite validar la hipótesis de resonancia vs disonancia.',
    theoreticalReference: 'Herbert Simon (Artefactos), Claudio Cioffi-Revilla (CSS), James C. Scott (Infrapoder) y Max Weber / Michael Löwy (Afinidad Electiva).',
    config: {
      ...DEFAULT_CONFIG,
      populationProletariat: 2,
      populationCapitalist: 1,
      populationTechnocracy: 0,
      populationReserveArmy: 0,
      alphaInitial: 0.25,
      alarmThreshold: 0.60,
      phiBase: 0.60, // Resonancia
      infrapowerMin: 0.10,
      infrapowerMax: 0.77,
      spatialRadius: 100, // Siempre interactúan
    },
    customInitialAgents: (cfg) => [
      {
        id: 'agent-sani',
        name: 'Sani',
        socialClass: SocialClass.PROLETARIAT,
        interior: 10.0,
        alienation: 90.0,
        infrapowerRaw: 0.35,
        infrapowerEffective: 0.35,
        activePhi: 0.6,
        affinityDescription: 'Resonancia con Djago',
        classConsciousness: 0.6,
        capital: 10.0,
        laborPower: 10.0,
        wage: cfg.baseWage,
        isStriking: false,
        tactic: ActionTactic.INFRAPODER_MICROSCOPICO,
        x: 40,
        y: 50,
        vx: 0.1,
        vy: -0.1,
        neighborsCount: 1,
      },
      {
        id: 'agent-djago',
        name: 'Djago',
        socialClass: SocialClass.PROLETARIAT,
        interior: 15.0,
        alienation: 85.0,
        infrapowerRaw: 0.40,
        infrapowerEffective: 0.40,
        activePhi: 0.6,
        affinityDescription: 'Resonancia con Sani',
        classConsciousness: 0.65,
        capital: 12.0,
        laborPower: 10.0,
        wage: cfg.baseWage,
        isStriking: false,
        tactic: ActionTactic.INFRAPODER_MICROSCOPICO,
        x: 60,
        y: 50,
        vx: -0.1,
        vy: 0.1,
        neighborsCount: 1,
      },
      {
        id: 'agent-machine-avatar',
        name: 'The Machine (Hegemón)',
        socialClass: SocialClass.CAPITALIST,
        interior: 95.0,
        alienation: 5.0,
        infrapowerRaw: 0.0,
        infrapowerEffective: 0.0,
        activePhi: 0.0,
        affinityDescription: 'Aparato asimilador',
        classConsciousness: 0.95,
        capital: 200.0,
        laborPower: 2.0,
        wage: 0,
        isStriking: false,
        tactic: ActionTactic.DISCIPLINA_PATRONAL,
        x: 50,
        y: 20,
        vx: 0,
        vy: 0,
        neighborsCount: 0,
      }
    ],
    customInitialMachine: {
      exterior: 100.0,
      alfa: 0.25,
      regime: SystemRegime.CONSENSO_HEGEMONICO,
      movementExterior: 0,
      alarmCount: 0,
      constantCapital: 100,
      variableCapital: 10,
      surplusValue: 15,
      organicComposition: 10,
      rateOfProfit: 0.136,
      rateOfSurplusValue: 1.5,
      averageInfrapower: 0.35,
      averageAlienation: 87.5,
      averagePhi: 0.6,
      giniCoefficient: 0.65,
      strikeParticipation: 0,
    }
  },
  {
    id: 'marx-trpf-crisis',
    title: 'Tendencia Decreciente de la Ganancia (TRPF Marx)',
    subtitle: 'Composición Orgánica c/v creciente y Crisis de Valorización',
    description: 'La competencia capitalista impulsa la mecanización tecnológica (aumento de capital constante c respecto a v). La tasa de ganancia general declina, forzando a The Machine a endurecer la disciplina laboral y elevar alfa, lo que provoca la insurrección del infrapoder subalterno.',
    theoreticalReference: 'Karl Marx (El Capital, Tomo III, Sección III: "Ley de la tendencia decreciente de la cuota de ganancia").',
    config: {
      ...DEFAULT_CONFIG,
      populationProletariat: 35,
      populationCapitalist: 6,
      populationTechnocracy: 4,
      populationReserveArmy: 10,
      mechanizationSpeed: 9.0, // Muy rápida tecnificación
      alphaInitial: 0.22,
      alarmThreshold: 0.55,
      phiBase: 0.35,
      infrapowerMin: 0.15,
      infrapowerMax: 0.85,
    }
  },
  {
    id: 'scott-infrapower-arms',
    title: 'Las Armas de los Débiles (James C. Scott)',
    subtitle: 'Infrapoder Subalterno, Disimulo y Resistencia Cotidiana',
    description: 'Sin recurrir a la huelga abierta que atraería la represión violenta de The Machine, el proletariado ejerce un infrapoder molecular constante: lentitud calculada, sabotaje microscópico y transcripciones ocultas. The Machine entra en paranoia de alarma intermitente.',
    theoreticalReference: 'James C. Scott ("Weapons of the Weak: Everyday Forms of Peasant Resistance" y "Domination and the Arts of Resistance").',
    config: {
      ...DEFAULT_CONFIG,
      populationProletariat: 40,
      populationCapitalist: 4,
      populationTechnocracy: 3,
      populationReserveArmy: 6,
      infrapowerMin: 0.35,
      infrapowerMax: 0.80,
      alarmThreshold: 0.50,
      phiBase: 0.10,
      spatialRadius: 22,
    }
  },
  {
    id: 'gramsci-hegemony-dissonance',
    title: 'Hegemonía y Fragmentación Disonante (Gramsci)',
    subtitle: 'Falsa Conciencia, Disonancia φ < 0 y Subsunción Adaptativa',
    description: 'The Machine logra mantener un régimen de consenso mediante la fragmentación de la afinidad electiva obrera (φ < 0). Los trabajadores compiten entre sí; el infrapoder colectivo se atenúa y la discrepancia se reduce por domesticación del interior sin necesidad de armas.',
    theoreticalReference: 'Antonio Gramsci ("Cuadernos de la Cárcel": Hegemonía, Bloque Histórico y Sentido Común).',
    config: {
      ...DEFAULT_CONFIG,
      populationProletariat: 30,
      populationCapitalist: 5,
      populationTechnocracy: 5,
      populationReserveArmy: 12,
      phiBase: -0.55, // Alta disonancia e individualización
      alphaInitial: 0.18,
      alarmThreshold: 0.70,
      infrapowerMin: 0.05,
      infrapowerMax: 0.45,
    }
  },
  {
    id: 'weber-lowy-elective-affinity',
    title: 'Resonancia Colectiva y Afinidad Electiva (Weber & Löwy)',
    subtitle: 'Convergencia Cultural, Potenciación Mutua y Huelga Resonante',
    description: 'Una comunidad subalterna con alta afinidad electiva (φ = +0.75). En el espacio social, el encuentro entre artefactos duplica su infrapoder efectivo, transformando la resistencia individual en una red resonante capaz de paralizar la valorización del capital.',
    theoreticalReference: 'Max Weber ("La ética protestante...") y Michael Löwy ("Redención y Utopía: Afinidades Electivas").',
    config: {
      ...DEFAULT_CONFIG,
      populationProletariat: 32,
      populationCapitalist: 4,
      populationTechnocracy: 2,
      populationReserveArmy: 5,
      phiBase: 0.75, // Máxima afinidad
      phiVolatility: 0.08,
      spatialRadius: 25,
      alarmThreshold: 0.58,
    }
  }
];
